// Code generated by "stringer -type=ExportType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[exportTypeUnknown-0]
	_ = x[exportTypeExported-1]
	_ = x[exportTypeUnexported-2]
}

const _ExportType_name = "ExportTypeUnknownExportTypeExportedExportTypeUnexported"

var _ExportType_index = [...]uint8{0, 17, 35, 55}

func (i exportType) String() string {
	if i < 0 || i >= exportType(len(_ExportType_index)-1) {
		return "ExportType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExportType_name[_ExportType_index[i]:_ExportType_index[i+1]]
}
